// AUTO-GENERATED by scripts/generate-hero-palettes.mjs — do not edit by hand.
// Per-champion colour identities sampled from the portrait art in public/heroes.
export interface HeroPalette { primary: string; secondary: string; accent: string; glow: string }

export const HERO_PALETTES: Record<string, HeroPalette> = {
  "knight_01": {
    "primary": "#685039",
    "secondary": "#746b5d",
    "accent": "#d2955f",
    "glow": "#42362f"
  },
  "knight_02": {
    "primary": "#5d452d",
    "secondary": "#66523a",
    "accent": "#d28140",
    "glow": "#7f7262"
  },
  "knight_03": {
    "primary": "#51331e",
    "secondary": "#47423e",
    "accent": "#d25632",
    "glow": "#41241b"
  },
  "knight_04": {
    "primary": "#353f4a",
    "secondary": "#39444f",
    "accent": "#6c9dd2",
    "glow": "#22262f"
  },
  "knight_05": {
    "primary": "#663828",
    "secondary": "#53332a",
    "accent": "#d24637",
    "glow": "#3f2829"
  },
  "undead_01": {
    "primary": "#402b75",
    "secondary": "#432a74",
    "accent": "#746ad2",
    "glow": "#44376d"
  },
  "undead_02": {
    "primary": "#493149",
    "secondary": "#3a3233",
    "accent": "#922ed2",
    "glow": "#2e2d37"
  },
  "undead_03": {
    "primary": "#3b3d2f",
    "secondary": "#3a3d2e",
    "accent": "#d28d6c",
    "glow": "#475338"
  },
  "undead_04": {
    "primary": "#343b4a",
    "secondary": "#343b49",
    "accent": "#54c7d2",
    "glow": "#262f42"
  },
  "undead_05": {
    "primary": "#40344d",
    "secondary": "#433347",
    "accent": "#8d64d2",
    "glow": "#2a2236"
  },
  "demon_01": {
    "primary": "#512d17",
    "secondary": "#4f332c",
    "accent": "#d26243",
    "glow": "#713d21"
  },
  "demon_02": {
    "primary": "#433155",
    "secondary": "#3e2f38",
    "accent": "#a455d2",
    "glow": "#33333e"
  },
  "demon_03": {
    "primary": "#572215",
    "secondary": "#7e3919",
    "accent": "#d26240",
    "glow": "#452013"
  },
  "demon_04": {
    "primary": "#682a1b",
    "secondary": "#5d2719",
    "accent": "#d24e30",
    "glow": "#5d2c17"
  },
  "demon_05": {
    "primary": "#442e5d",
    "secondary": "#4b2b60",
    "accent": "#9761d2",
    "glow": "#341455"
  },
  "elf_01": {
    "primary": "#4a4637",
    "secondary": "#656356",
    "accent": "#d2b361",
    "glow": "#5f625a"
  },
  "elf_02": {
    "primary": "#383d34",
    "secondary": "#383b31",
    "accent": "#d29066",
    "glow": "#526343"
  },
  "elf_03": {
    "primary": "#1d484c",
    "secondary": "#4e6360",
    "accent": "#46c5d2",
    "glow": "#2c2e35"
  },
  "elf_04": {
    "primary": "#403737",
    "secondary": "#504031",
    "accent": "#d29561",
    "glow": "#463a34"
  },
  "elf_05": {
    "primary": "#3d3b2e",
    "secondary": "#444231",
    "accent": "#d2b862",
    "glow": "#414539"
  },
  "barbarian_01": {
    "primary": "#56321e",
    "secondary": "#4a2b20",
    "accent": "#d26144",
    "glow": "#59332a"
  },
  "barbarian_02": {
    "primary": "#423833",
    "secondary": "#40322a",
    "accent": "#d28d69",
    "glow": "#382d27"
  },
  "barbarian_03": {
    "primary": "#473630",
    "secondary": "#392c26",
    "accent": "#d28766",
    "glow": "#2b2e39"
  },
  "barbarian_04": {
    "primary": "#3b3e42",
    "secondary": "#3d3b3c",
    "accent": "#689fd2",
    "glow": "#304959"
  },
  "barbarian_05": {
    "primary": "#602e1a",
    "secondary": "#573123",
    "accent": "#d24024",
    "glow": "#3c1b15"
  },
  "darkelf_01": {
    "primary": "#35394f",
    "secondary": "#3a3c4a",
    "accent": "#6b96d2",
    "glow": "#585f71"
  },
  "darkelf_02": {
    "primary": "#3c3938",
    "secondary": "#3e3937",
    "accent": "#d2856d",
    "glow": "#2f2e2f"
  },
  "darkelf_03": {
    "primary": "#52316c",
    "secondary": "#472f55",
    "accent": "#924dd2",
    "glow": "#34254c"
  },
  "darkelf_04": {
    "primary": "#452d60",
    "secondary": "#443152",
    "accent": "#712dd2",
    "glow": "#261948"
  },
  "darkelf_05": {
    "primary": "#2b3442",
    "secondary": "#3e4856",
    "accent": "#6c96d2",
    "glow": "#4c5462"
  },
  "special_01": {
    "primary": "#58341d",
    "secondary": "#473327",
    "accent": "#d27d65",
    "glow": "#4a3a36"
  },
  "special_02": {
    "primary": "#8c6c40",
    "secondary": "#8c6736",
    "accent": "#d2782c",
    "glow": "#b69157"
  },
  "special_03": {
    "primary": "#402b75",
    "secondary": "#432a74",
    "accent": "#746ad2",
    "glow": "#44376d"
  },
  "special_04": {
    "primary": "#344030",
    "secondary": "#31452c",
    "accent": "#74d277",
    "glow": "#324630"
  },
  "special_05": {
    "primary": "#35394f",
    "secondary": "#3a3c4a",
    "accent": "#6b96d2",
    "glow": "#585f71"
  }
};

export function getHeroPalette(templateId: string): HeroPalette {
  return HERO_PALETTES[templateId] ?? { primary: '#6b7280', secondary: '#4b5563', accent: '#c9a227', glow: '#312e81' };
}
