'use client';

// ─────────────────────────────────────────────────────────────────
// Hero3DModel v3 — generated 3D champions.
//
// Every champion gets a sculpted miniature whose look is *derived from
// their own portrait art*: colours come from src/lib/hero-palettes.ts
// (auto-generated by scripts/generate-hero-palettes.mjs, which samples
// each portrait), the face is the portrait itself mapped onto the head,
// and the body silhouette / headgear / weapon follow the hero's class
// and faction. Rarity adds capes, halos and auras. No external 3D
// assets — pure primitives + lathe profiles, fully offline.
// ─────────────────────────────────────────────────────────────────

import { useFrame } from '@react-three/fiber';
import { useTexture } from '@react-three/drei';
import { Suspense, useMemo, useRef } from 'react';
import * as THREE from 'three';
import type { BattleHero } from '@/lib/game-data';
import { getHeroImageUrl } from '@/lib/hero-images';
import { getHeroPalette } from '@/lib/hero-palettes';

type HeroClass = 'knight' | 'mage' | 'archer' | 'reaper' | 'fiend';

function classOf(hero: BattleHero): HeroClass {
  const s = `${hero.name} ${hero.skill1Name} ${hero.skill2Name} ${hero.skill3Name}`.toLowerCase();
  if (/archer|ranger|hunter|\bbow\b|arrow|eagle|volley|marks|precise/.test(s)) return 'archer';
  if (/mage|sorc|necro|witch|warlock|wizard|arcane|frost|flame burst|spell|staff|conjur|orb|elowen/.test(s)) return 'mage';
  if (hero.faction === 'undead') return 'reaper';
  if (hero.faction === 'demon') return 'fiend';
  return 'knight';
}

// Body silhouette profiles for LatheGeometry: [radius, height] pairs
// from the hem up to the neck (heights are relative, scaled below).
const BODY_PROFILE: Record<HeroClass, [number, number][]> = {
  knight: [[0.30, 0], [0.34, 0.08], [0.27, 0.28], [0.25, 0.5], [0.34, 0.72], [0.31, 0.92], [0.12, 1.0]],
  mage:   [[0.52, 0], [0.44, 0.14], [0.24, 0.5], [0.27, 0.72], [0.25, 0.92], [0.11, 1.0]],
  archer: [[0.28, 0], [0.25, 0.12], [0.20, 0.45], [0.25, 0.72], [0.23, 0.92], [0.10, 1.0]],
  reaper: [[0.46, 0], [0.34, 0.16], [0.17, 0.5], [0.22, 0.74], [0.20, 0.92], [0.10, 1.0]],
  fiend:  [[0.30, 0], [0.30, 0.1], [0.28, 0.4], [0.40, 0.72], [0.35, 0.92], [0.13, 1.0]],
};

const BODY_BASE = 0.26;  // sits on the pedestal
const BODY_H = 1.08;     // hem → neck
const NECK_Y = BODY_BASE + BODY_H;
const HEAD_Y = NECK_Y + 0.26;

// Portrait face crop (portraits are 3:4 with the head upper-centre).
const FACE_CROP = { ox: 0.33, oy: 0.70, rw: 0.34, rh: 0.23 };

function Face({ url }: { url: string }) {
  const tex = useTexture(url);
  const cropped = useMemo(() => {
    const t = tex.clone();
    t.colorSpace = THREE.SRGBColorSpace;
    t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping;
    t.repeat.set(FACE_CROP.rw, FACE_CROP.rh);
    t.offset.set(FACE_CROP.ox, FACE_CROP.oy);
    t.needsUpdate = true;
    return t;
  }, [tex]);
  return (
    <mesh position={[0, -0.01, 0.185]}>
      <planeGeometry args={[0.34, 0.38]} />
      <meshBasicMaterial map={cropped} toneMapped={false} />
    </mesh>
  );
}

function Weapon({ cls, accent, element }: { cls: HeroClass; accent: string; element: string }) {
  switch (cls) {
    case 'mage':
      return (
        <group>
          <mesh><cylinderGeometry args={[0.028, 0.034, 1.35, 8]} /><meshStandardMaterial color="#4a3018" roughness={0.7} /></mesh>
          <mesh position={[0, 0.74, 0]}><icosahedronGeometry args={[0.11, 1]} /><meshStandardMaterial color={element} emissive={element} emissiveIntensity={1.6} /></mesh>
          <mesh position={[0, 0.74, 0]}><icosahedronGeometry args={[0.16, 1]} /><meshBasicMaterial color={element} transparent opacity={0.25} blending={THREE.AdditiveBlending} depthWrite={false} /></mesh>
        </group>
      );
    case 'archer':
      return (
        <group rotation={[0, 0, Math.PI / 2]}>
          <mesh><torusGeometry args={[0.4, 0.026, 8, 24, Math.PI * 1.2]} /><meshStandardMaterial color="#5d3a1c" roughness={0.6} /></mesh>
          <mesh rotation={[0, 0, Math.PI * 0.1]}><cylinderGeometry args={[0.004, 0.004, 0.74, 4]} /><meshStandardMaterial color="#d9d9d9" /></mesh>
        </group>
      );
    case 'reaper':
      return (
        <group>
          <mesh><cylinderGeometry args={[0.03, 0.03, 1.45, 8]} /><meshStandardMaterial color="#242424" roughness={0.6} /></mesh>
          <mesh position={[0.3, 0.7, 0]} rotation={[0, 0, -1.05]}><boxGeometry args={[0.58, 0.1, 0.03]} /><meshStandardMaterial color={accent} metalness={0.85} roughness={0.2} emissive={accent} emissiveIntensity={0.25} /></mesh>
        </group>
      );
    case 'fiend':
      return (
        <group>
          {[-0.09, 0, 0.09].map((x, i) => (
            <mesh key={i} position={[x, 0.14, 0]} rotation={[0.25, 0, 0]}>
              <coneGeometry args={[0.028, 0.36, 6]} />
              <meshStandardMaterial color={accent} metalness={0.7} roughness={0.3} emissive={accent} emissiveIntensity={0.3} />
            </mesh>
          ))}
        </group>
      );
    case 'knight':
    default:
      return (
        <group>
          <mesh position={[0, 0.46, 0]}><boxGeometry args={[0.075, 0.86, 0.022]} /><meshStandardMaterial color="#e8eef7" metalness={0.95} roughness={0.15} /></mesh>
          <mesh position={[0, 0.47, 0]}><boxGeometry args={[0.02, 0.8, 0.026]} /><meshStandardMaterial color={accent} metalness={0.8} roughness={0.3} emissive={accent} emissiveIntensity={0.2} /></mesh>
          <mesh position={[0, 0.02, 0]}><boxGeometry args={[0.3, 0.055, 0.055]} /><meshStandardMaterial color={accent} metalness={0.85} roughness={0.25} /></mesh>
          <mesh position={[0, -0.15, 0]}><cylinderGeometry args={[0.028, 0.028, 0.26, 8]} /><meshStandardMaterial color="#4a3018" roughness={0.7} /></mesh>
        </group>
      );
  }
}

function Headgear({ hero, cls, pal }: { hero: BattleHero; cls: HeroClass; pal: { primary: string; secondary: string; accent: string } }) {
  const f = hero.faction;
  if (f === 'demon') {
    return (
      <group>
        {[-1, 1].map((s) => (
          <mesh key={s} position={[s * 0.16, 0.22, 0]} rotation={[0, 0, -s * 0.5]}>
            <coneGeometry args={[0.05, 0.3, 8]} />
            <meshStandardMaterial color="#2b2018" roughness={0.5} />
          </mesh>
        ))}
        <mesh position={[0, 0.2, 0]}><boxGeometry args={[0.38, 0.09, 0.36]} /><meshStandardMaterial color={pal.secondary} roughness={0.6} /></mesh>
      </group>
    );
  }
  if (f === 'elf' || f === 'darkelf' || cls === 'archer' || cls === 'reaper' || cls === 'mage') {
    // Hood
    return (
      <group>
        <mesh position={[0, 0.1, -0.045]}>
          <sphereGeometry args={[0.26, 20, 16, 0, Math.PI * 2, 0, Math.PI * 0.62]} />
          <meshStandardMaterial color={pal.primary} roughness={0.75} side={THREE.DoubleSide} />
        </mesh>
        <mesh position={[0, 0.24, 0]}><boxGeometry args={[0.4, 0.05, 0.38]} /><meshStandardMaterial color={pal.accent} metalness={0.5} roughness={0.4} /></mesh>
      </group>
    );
  }
  // Knights / barbarians: crested helm band
  return (
    <group>
      <mesh position={[0, 0.2, 0]}><boxGeometry args={[0.4, 0.1, 0.38]} /><meshStandardMaterial color={pal.secondary} metalness={0.75} roughness={0.3} /></mesh>
      <mesh position={[0, 0.3, -0.02]} rotation={[0.15, 0, 0]}><boxGeometry args={[0.06, 0.12, 0.3]} /><meshStandardMaterial color={pal.accent} emissive={pal.accent} emissiveIntensity={0.25} roughness={0.4} /></mesh>
    </group>
  );
}

interface HeroModelProps {
  hero: BattleHero;
  isActive: boolean;
  facing: number;
  rarityColor: string;
  elementColor: string;
}

export function Hero3DModel({ hero, isActive, facing, rarityColor, elementColor }: HeroModelProps) {
  const url = getHeroImageUrl(hero.templateId);
  const pal = getHeroPalette(hero.templateId);
  const cls = useMemo(() => classOf(hero), [hero.templateId]);

  const bodyGeom = useMemo(() => {
    const pts = BODY_PROFILE[cls].map(([r, h]) => new THREE.Vector2(r, h * BODY_H));
    return new THREE.LatheGeometry(pts, 24);
  }, [cls]);

  const root = useRef<THREE.Group>(null);
  const armRef = useRef<THREE.Group>(null);
  const wasActive = useRef(false);
  const swingStart = useRef(-10);
  const seed = useMemo(() => (hero.maxHealth % 97) * 0.13, [hero.maxHealth]);

  const baseRotation = facing > 0 ? -0.5 : Math.PI + 0.5; // 3/4 toward enemy+camera

  useFrame((state) => {
    const now = state.clock.elapsedTime;
    if (root.current) {
      root.current.rotation.y = baseRotation + Math.sin(now * 1.1 + seed) * 0.045;
      root.current.position.y = Math.sin(now * 1.5 + seed) * 0.015;
    }
    if (isActive && !wasActive.current) swingStart.current = now;
    wasActive.current = isActive;
    if (armRef.current) {
      const t = (now - swingStart.current) / 0.5;
      armRef.current.rotation.x = t >= 0 && t <= 1 ? -0.35 + Math.sin(t * Math.PI) * -1.9 : -0.35;
    }
  });

  const dead = !hero.isAlive;
  const tint = dead ? '#4c4c4c' : undefined;
  const hasCape = ['epic', 'legendary', 'mythic'].includes(hero.rarity);
  const hasHalo = ['legendary', 'mythic'].includes(hero.rarity);

  return (
    <group ref={root} rotation={[0, baseRotation, 0]}>
      {/* Body (class silhouette, hero-palette primary) */}
      <mesh geometry={bodyGeom} position={[0, BODY_BASE, 0]} castShadow>
        <meshStandardMaterial color={tint ?? pal.primary} metalness={cls === 'knight' || cls === 'fiend' ? 0.55 : 0.15} roughness={cls === 'knight' ? 0.35 : 0.65} />
      </mesh>
      {/* Chest plate / sash (secondary) */}
      <mesh position={[0, BODY_BASE + BODY_H * 0.72, 0]} castShadow>
        <cylinderGeometry args={[0.305, 0.33, 0.3, 20]} />
        <meshStandardMaterial color={tint ?? pal.secondary} metalness={0.45} roughness={0.4} />
      </mesh>
      {/* Belt (accent) */}
      <mesh position={[0, BODY_BASE + BODY_H * 0.5, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <torusGeometry args={[0.255, 0.035, 8, 22]} />
        <meshStandardMaterial color={tint ?? pal.accent} metalness={0.7} roughness={0.3} emissive={pal.accent} emissiveIntensity={dead ? 0 : 0.2} />
      </mesh>
      {/* Rarity chest gem */}
      <mesh position={[0, BODY_BASE + BODY_H * 0.76, 0.3]}>
        <icosahedronGeometry args={[0.06, 0]} />
        <meshStandardMaterial color={rarityColor} emissive={rarityColor} emissiveIntensity={dead ? 0.1 : 0.9} metalness={0.6} roughness={0.2} />
      </mesh>

      {/* Shoulders */}
      {(cls === 'knight' || cls === 'fiend') && [-1, 1].map((s) => (
        <mesh key={s} position={[s * 0.34, NECK_Y - 0.14, 0]} castShadow>
          <sphereGeometry args={[0.15, 14, 14]} />
          <meshStandardMaterial color={tint ?? pal.secondary} metalness={0.7} roughness={0.3} />
        </mesh>
      ))}

      {/* Cape for epic+ (hero glow colour) */}
      {hasCape && (
        <mesh position={[0, BODY_BASE + BODY_H * 0.62, -0.3]} rotation={[0.16, 0, 0]}>
          <planeGeometry args={[0.62, 1.0, 1, 4]} />
          <meshStandardMaterial color={tint ?? pal.glow} side={THREE.DoubleSide} roughness={0.7} emissive={pal.glow} emissiveIntensity={dead ? 0 : 0.25} />
        </mesh>
      )}

      {/* Left arm */}
      <group position={[-0.34, NECK_Y - 0.18, 0]} rotation={[0.15, 0, 0.35]}>
        <mesh position={[0, -0.24, 0]} castShadow><capsuleGeometry args={[0.06, 0.36, 4, 10]} /><meshStandardMaterial color={tint ?? pal.secondary} roughness={0.55} /></mesh>
      </group>
      {/* Right arm + weapon (swings on attack) */}
      <group ref={armRef} position={[0.34, NECK_Y - 0.16, 0]} rotation={[-0.35, 0, 0]}>
        <mesh position={[0, -0.24, 0]} castShadow><capsuleGeometry args={[0.06, 0.36, 4, 10]} /><meshStandardMaterial color={tint ?? pal.secondary} roughness={0.55} /></mesh>
        <group position={[0, -0.47, 0.1]} rotation={[1.15, 0, 0]}>
          <Weapon cls={cls} accent={pal.accent} element={elementColor} />
        </group>
      </group>

      {/* Head: portrait face + faction headgear */}
      <group position={[0, HEAD_Y, 0]}>
        <mesh castShadow>
          <boxGeometry args={[0.37, 0.4, 0.36]} />
          <meshStandardMaterial color={tint ?? pal.secondary} roughness={0.6} />
        </mesh>
        {url && !dead ? (
          <Suspense fallback={null}>
            <Face url={url} />
          </Suspense>
        ) : (
          <mesh position={[0, -0.01, 0.185]}><planeGeometry args={[0.34, 0.38]} /><meshStandardMaterial color="#3a3a3a" /></mesh>
        )}
        <Headgear hero={hero} cls={cls} pal={pal} />
      </group>

      {/* Legendary+ halo */}
      {hasHalo && !dead && (
        <mesh position={[0, HEAD_Y + 0.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <torusGeometry args={[0.2, 0.02, 8, 28]} />
          <meshStandardMaterial color={rarityColor} emissive={rarityColor} emissiveIntensity={1.4} />
        </mesh>
      )}
    </group>
  );
}
